name: 'DeployNow template rendering'
description: 'Fill templates of configuration files before deployment'
inputs:
  deployment-id:
    description: 'The id of the current deployment'
    required: false
  input-directory:
    description: 'The directory to search for template files'
    required: true
  output-directory:
    description: 'The directory where the processed templates will be written to'
    required: true
  intermediate-data-file:
    description: 'A file used to store information about prepared templates when using this action in multiple steps'
    required: false
  template-extension:
    description: 'The file extension which identifies template files'
    required: true
    default: '.template'
  use-context-sensitive-references:
    description: 'Use valid urls und port numbers for intermediate references when using this action in multiple steps'
    required: true
    default: 'true'
  data:
    description: 'Data to use for rendering templates as json objects'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
