name: 'DeployNow template rendering'
description: 'Fill templates of configuration files before deployment based on the golang template engine'
inputs:
  template-directory:
    description: 'The directory to search for template files'
    required: false
    default: '.deploy-now'
  template-extension:
    description: 'The file extension which identifies template files'
    required: false
    default: '.template'
  output-directory:
    description: 'The directory where the processed templates will be written to'
    required: false
    default: './'
  secrets:
    description: 'Data to use for rendering templates as yaml or json objects'
    required: true
outputs:
  used_runtime_values:
    description: 'Used runtime values to replace them with another template engine later'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/ionos-deploy-now/template-renderer:v1.0.0'
  args:
    - '--template-dir'
    - ${{ inputs.template-directory }}
    - '--template-extension'
    - ${{ inputs.template-extension }}
    - '--output-dir'
    - ${{ inputs.output-directory }}
    - '--secrets'
    - ${{ inputs.secrets }}
    - '--runtime'
    - '{"db": {"user": "$DB_USER", "password": "$DB_PASSWORD", "url": "$DB_URL"}}'
    - '--copy-permissions'
    - '--output-runtime'